name: Check
on:
  pull_request:
    paths:
      - '**/migrations/**'
jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1

      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            if [[ $file != *"migrations"* ]]; then
              echo "Invalid PR please split it up" && exit 1
            fi
          done
          